---
- name: PHP-FPMインストール
  yum: name={{ item.name }} state=latest
  with_items: phpfpm.package

- name: PHP-FPM設定ファイル設置
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf
  notify:
   - restart php-fpm

- name: PHP-FPMサービス起動追加
  service: name=php-fpm state=running enabled=yes
