---
- name: MongoDBレポジトリ追加
  template: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo

- name: MongoDBインストール(stable版)
  yum: name={{ item.name }} state=latest
  with_items : mongo.packages

- name: MongoDB設定ファイル設置
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  notify:
   - restart mongo

- name: Mongoサービス起動追加
  service: name=mongod state=running enabled=yes
